
//! Autogenerated weights for `pallet_teeracle`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-07-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `caribe`, CPU: `12th Gen Intel(R) Core(TM) i7-1260P`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("integritee-solo-fresh"), DB CACHE: 1024

// Executed Command:
// target/release/integritee-node
// benchmark
// pallet
// --chain=integritee-solo-fresh
// --steps=50
// --repeat=20
// --pallet=pallet_teeracle
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=runtime/src/weights/pallet_teeracle.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_teeracle`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_teeracle::WeightInfo for WeightInfo<T> {
	/// Storage: Teerex SovereignEnclaves (r:1 w:0)
	/// Proof Skipped: Teerex SovereignEnclaves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Teeracle Whitelists (r:1 w:0)
	/// Proof Skipped: Teeracle Whitelists (max_values: None, max_size: None, mode: Measured)
	/// Storage: Teeracle ExchangeRates (r:1 w:1)
	/// Proof Skipped: Teeracle ExchangeRates (max_values: None, max_size: None, mode: Measured)
	fn update_exchange_rate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `433`
		//  Estimated: `3898`
		// Minimum execution time: 19_504_000 picoseconds.
		Weight::from_parts(21_163_000, 0)
			.saturating_add(Weight::from_parts(0, 3898))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Teerex SovereignEnclaves (r:1 w:0)
	/// Proof Skipped: Teerex SovereignEnclaves (max_values: None, max_size: None, mode: Measured)
	/// Storage: Teeracle Whitelists (r:1 w:0)
	/// Proof Skipped: Teeracle Whitelists (max_values: None, max_size: None, mode: Measured)
	/// Storage: Teeracle OracleData (r:0 w:1)
	/// Proof Skipped: Teeracle OracleData (max_values: None, max_size: None, mode: Measured)
	fn update_oracle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `424`
		//  Estimated: `3889`
		// Minimum execution time: 17_429_000 picoseconds.
		Weight::from_parts(18_755_000, 0)
			.saturating_add(Weight::from_parts(0, 3889))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Teeracle Whitelists (r:1 w:1)
	/// Proof Skipped: Teeracle Whitelists (max_values: None, max_size: None, mode: Measured)
	fn add_to_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3471`
		// Minimum execution time: 10_086_000 picoseconds.
		Weight::from_parts(10_929_000, 0)
			.saturating_add(Weight::from_parts(0, 3471))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Teeracle Whitelists (r:1 w:1)
	/// Proof Skipped: Teeracle Whitelists (max_values: None, max_size: None, mode: Measured)
	fn remove_from_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `107`
		//  Estimated: `3572`
		// Minimum execution time: 11_891_000 picoseconds.
		Weight::from_parts(12_276_000, 0)
			.saturating_add(Weight::from_parts(0, 3572))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
