//! Autogenerated weights for `pallet_utility`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2021-11-11, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("integritee-solo-fresh"), DB CACHE: 128

// Executed Command:
// ./integritee-node
// benchmark
// --chain=integritee-solo-fresh
// --steps=50
// --repeat=20
// --pallet=pallet_utility
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=runtime/src/weights/pallet_utility.rs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for pallet_utility.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_utility::WeightInfo for WeightInfo<T> {
	fn batch(c: u32, ) -> Weight {
		Weight::from_parts(63_793_000, 0u64)
			// Standard Error: 36_000
			.saturating_add(Weight::from_parts(9_370_000, 0u64))
			.saturating_mul(c.into())
	}
	fn as_derivative() -> Weight {
		Weight::from_parts(4_912_000, 0u64)
	}
	fn batch_all(c: u32, ) -> Weight {
		Weight::from_parts(58_530_000, 0u64)
			// Standard Error: 20_000
			.saturating_add(Weight::from_parts(10_017_000, 0u64))
			.saturating_mul(c.into())
	}
	//TODO: update weight value
	fn dispatch_as() -> Weight {
		Weight::from_parts(14_340_000, 0u64)
	}
	/// The range of component `c` is `[0, 1000]`.
	fn force_batch(c: u32, ) -> Weight {
		Weight::from_parts(19_136_000, 0u64)
			// Standard Error: 2_000
			.saturating_add(Weight::from_parts(2_697_000, 0u64))
			.saturating_mul(c.into())
	}
}
