
//! Autogenerated weights for `pallet_proxy`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2021-11-11, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("integritee-solo-fresh"), DB CACHE: 128

// Executed Command:
// ./integritee-node
// benchmark
// --chain=integritee-solo-fresh
// --steps=50
// --repeat=20
// --pallet=pallet_proxy
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=runtime/src/weights/pallet_proxy.rs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for pallet_proxy.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_proxy::WeightInfo for WeightInfo<T> {
	// Storage: Proxy Proxies (r:1 w:0)
	fn proxy(p: u32, ) -> Weight {
		Weight::from_parts(49_346_000, 0u64)
			// Standard Error: 15_000
			.saturating_add(Weight::from_parts(423_000, 0u64)).saturating_mul(p.into())
			.saturating_add(T::DbWeight::get().reads(1))
	}
	// Storage: Proxy Proxies (r:1 w:0)
	// Storage: Proxy Announcements (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn proxy_announced(a: u32, p: u32, ) -> Weight {
		Weight::from_parts(108_778_000, 0u64)
			// Standard Error: 78_000
			.saturating_add(Weight::from_parts(985_000, 0u64)).saturating_mul(a.into())
			// Standard Error: 81_000
			.saturating_add(Weight::from_parts(472_000, 0u64)).saturating_mul(p.into())
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: Proxy Announcements (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn remove_announcement(a: u32, _p: u32, ) -> Weight {
		Weight::from_parts(80_354_000, 0u64)
			// Standard Error: 21_000
			.saturating_add(Weight::from_parts(1_101_000, 0u64)).saturating_mul(a.into())
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: Proxy Announcements (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn reject_announcement(a: u32, p: u32, ) -> Weight {
		Weight::from_parts(73_831_000, 0u64)
			// Standard Error: 53_000
			.saturating_add(Weight::from_parts(1_185_000, 0u64)).saturating_mul(a.into())
			// Standard Error: 55_000
			.saturating_add(Weight::from_parts(162_000, 0u64)).saturating_mul(p.into())
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: Proxy Proxies (r:1 w:0)
	// Storage: Proxy Announcements (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	fn announce(a: u32, p: u32, ) -> Weight {
		Weight::from_parts(97_013_000, 0u64)
			// Standard Error: 61_000
			.saturating_add(Weight::from_parts(1_224_000, 0u64)).saturating_mul(a.into())
			// Standard Error: 64_000
			.saturating_add(Weight::from_parts(500_000, 0u64)).saturating_mul(p.into())
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: Proxy Proxies (r:1 w:1)
	fn add_proxy(p: u32, ) -> Weight {
		Weight::from_parts(84_020_000, 0u64)
			// Standard Error: 55_000
			.saturating_add(Weight::from_parts(591_000, 0u64)).saturating_mul(p.into())
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Proxy Proxies (r:1 w:1)
	fn remove_proxy(p: u32, ) -> Weight {
		Weight::from_parts(78_733_000, 0u64)
			// Standard Error: 49_000
			.saturating_add(Weight::from_parts(234_000, 0u64)).saturating_mul(p.into())
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Proxy Proxies (r:1 w:1)
	fn remove_proxies(p: u32, ) -> Weight {
		Weight::from_parts(70_957_000, 0u64)
			// Standard Error: 15_000
			.saturating_add(Weight::from_parts(451_000, 0u64)).saturating_mul(p.into())
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Proxy Proxies (r:1 w:1)
	/// The range of component `p` is `[1, 31]`.
	fn create_pure(p: u32, ) -> Weight {
		// Minimum execution time: 48_409 nanoseconds.
		Weight::from_parts(55_098_467, 0u64)
			// Standard Error: 31_462
			.saturating_add(Weight::from_parts(38_634, 0u64).saturating_mul(p as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: Proxy Proxies (r:1 w:1)
	/// The range of component `p` is `[0, 30]`.
	fn kill_pure(p: u32, ) -> Weight {
		// Minimum execution time: 40_317 nanoseconds.
		Weight::from_parts(41_597_802, 0u64)
			// Standard Error: 15_439
			.saturating_add(Weight::from_parts(210_246, 0u64).saturating_mul(p as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
}
