name: CI

on:
  push:

jobs:
  ##############################################################################
  ##############################################################################
  cargo_test:
    runs-on: ubuntu-latest
    steps:
      - uses: Interstellar-Network/gh-actions/prepare@v3-dev
        with:
          ssh_key_input: ${{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI }}
          install_cmake_and_ninja: false
          install_ccache: true
          install_conan: false

      - uses: Interstellar-Network/gh-actions/prepare_rust@v3-dev
        with:
          use_toolchain_toml: "true"
          toolchain_components: "rustfmt,clippy"

      ##########################################################################

      # TODO pass "--features skip-ias-check,skip-extrinsic-filtering"; to cargo check? and/or cargo test?

      - uses: Interstellar-Network/gh-actions/rust-build-and-test@v3-dev

  ##############################################################################
  ##############################################################################
  cargo_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: Interstellar-Network/gh-actions/prepare@v3-dev
        with:
          ssh_key_input: ${{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI }}
          install_cmake_and_ninja: false
          install_ccache: true
          install_conan: false

      - uses: Interstellar-Network/gh-actions/prepare_rust@v3-dev
        with:
          use_toolchain_toml: "true"
          toolchain_components: "rustfmt,clippy"

      ##########################################################################

      # TODO pass "--features skip-ias-check,skip-extrinsic-filtering"; to cargo check? and/or cargo test?

      - uses: Interstellar-Network/gh-actions/rust-lint@v3-dev
